### ISSUE TITLE
Support for extra config

### ISSUE THREAD

**Issue by esselius** [valeriano-manassero/helm-charts#102]
I need to add auth config properties that's not available in the chart, like these: [Trino OAuth 2.0 authentication](https://trino.io/docs/current/security/oauth2.html)

I've been reading the templates but haven't found a way to inject arbitrary configuration or issues mentioning

**Comment by esselius** [comment]
I also got these errors and warnings when upgrading to 369:

```
Errors:

1) Defunct property 'query.max-total-memory-per-node' (class [class io.trino.memory.NodeMemoryConfig]) cannot be configured.
2) Configuration property 'query.max-total-memory-per-node' was not used

Warnings:

1) Configuration property 'discovery-server.enabled' is deprecated and should not be used

==========
```

Maybe the entire `config.properties` key needs to be replaceable so that the chart doesn't lock you to specific trino versions, given the rate of change over there

**Comment by valeriano-manassero** [comment]
ty for PR, much appreciated!
