### ISSUE TITLE
Bug in templates regarding authenticationType value

### ISSUE THREAD

**Issue by MaciejChyrc** [valeriano-manassero/helm-charts#120]
Hello. Today when upgrading from 1.15.0 to 2.0.0 I've noticed that `trino-password-authentication` secret is created when `config.general.authenticationType` is set to "PASSWORD" but the secret is mounted into coordinator's container when `config.coordinator.authenticationType` is set (notice that one is `general`, the other one is `coordinator`). I believe this is a bug as `config.coordinator.authenticationType` isn't mentioned in readme and `values.yaml`.  

I can submit a PR but I need to be sure which config value is correct. I believe it should be `config.general.authenticationType` as it's in readme but I may be wrong here.

**Comment by valeriano-manassero** [comment]
Oh you are absolutely right, if you can issue a PR would be great, ty!

**Comment by valeriano-manassero** [comment]
Merged and chart 2.0.1 automatically deployed. Ty for your help!
