### ISSUE TITLE
Autoscaler minReplicas refers to wrong value

### ISSUE THREAD

**Issue by MaciejChyrc** [valeriano-manassero/helm-charts#122]
When deploying trino with autoscaler enabled I noticed that workers kept scaling down to 1 even though I set `replicas` to 5. It turns out autoscaler's `minReplicas` uses `config.worker.workers` value instead of `config.worker.replicas` and I believe it's a bug introduced in version `2.0.0`.  
I've got a PR with a fix.

**Comment by valeriano-manassero** [comment]
Ty for PR, merged!
