### ISSUE TITLE
access denied to add columns to hive tables

### ISSUE THREAD

**Issue by gowdra01** [valeriano-manassero/helm-charts#129]
Hi , I am using trinodb in k8s and connected to hive.. but unfortunately I am getting Access Denied error when I trying to alter table to add columns ... I have added the rules.json and hive-secutiry for the user which logged in via ldap.. any idea why is that error ?

I can do show tables; or select query it work but not add columns

    rules.json: |-
      {
        "catalogs": [
          {
            "catalog": "hive",
            "allow": "all"
          }
        ],
        "queries": [
          {
            "user": "svc-presto",
            "allow": ["execute", "kill", "view"]
          }
        ]
      }

 ```
 hive-security.properties: |-
    {
      "schemas": [
        {
          "schema": ".*",
          "owner": true
        }
      ],
      "tables": [
        {
          "privileges": ["SELECT", "ALTER","DROP", "INSERT", "DELETE", "OWNERSHIP"]
        }
      ]
    }
```

**Comment by valeriano-manassero** [comment]
Since this looks a config problem not related Helm chart, maybe it's better to open an issue directly on Trino repo.
