### ISSUE TITLE
Issue while using https

### ISSUE THREAD

**Issue by ankitagupta122** [valeriano-manassero/helm-charts#130]
I am using this chart to use https for authentication with below properties:
config.properties (coordinator)

>  coordinator=true
>   node-scheduler.include-coordinator=false
>   http-server.http.port=8080
>   query.max-memory={{ .Values.server.config.coordinator.query.maxMemory }}
>   query.max-memory-per-node={{ .Values.server.config.coordinator.query.maxMemoryPerNode }}
>   discovery-server.enabled=true
>   discovery.uri=http://localhost:8080
>   http-server.authentication.type=PASSWORD
>   http-server.https.enabled=true
>   http-server.https.port=8443
>   http-server.https.keystore.path="/user/test/keystore/keystore.jks"
>   internal-communication.shared-secret=<>
>   http-server.https.keystore.key=<>

config.properties (worker)

> coordinator=false
>   http-server.http.port=8080
>   query.max-memory={{ .Values.server.config.worker.query.maxMemory }}
>   query.max-memory-per-node={{ .Values.server.config.worker.query.maxMemoryPerNode }}
>   discovery.uri=http://trino:8080
>   internal-communication.https.required=false
>   http-server.https.enabled=true
>   http-server.https.port=8443
>   http-server.https.keystore.path="/user/test/keystore/keystore.jks"
>   internal-communication.shared-secret=<>
>   http-server.https.keystore.key=<>

While deploying the helm, coordinator and worker are up and running, but logging into UI shows 0 active workers.
UI screenshot attached

<img width="1299" alt="Screenshot 2022-09-08 at 16 21 36" src="https://user-images.githubusercontent.com/82257452/189119059-da0ad20d-a315-4360-84f6-2d035631b67a.png">

**Comment by valeriano-manassero** [comment]
With this chart, TLS for HTTP is doable enabling Ingress controller; as far as I remember I never tested HTTPS directly from pod.
