### ISSUE TITLE
Move podAnnotations to their correct place

### ISSUE THREAD

**Issue by jkleinkauff** [valeriano-manassero/helm-charts#153]
Right now the following podAnnotations are doing nothing to deployment-coordinator or deployment-worker.

https://github.com/valeriano-manassero/helm-charts/blob/da1c0137e39807b903828867b100dcd93732b8e9/valeriano-manassero/trino/values.yaml#L57-L63

https://github.com/valeriano-manassero/helm-charts/blob/da1c0137e39807b903828867b100dcd93732b8e9/valeriano-manassero/trino/values.yaml#L85-L92

The templated deployment is looking for .Values.podAnnotations

https://github.com/valeriano-manassero/helm-charts/blob/da1c0137e39807b903828867b100dcd93732b8e9/valeriano-manassero/trino/templates/deployment-worker.yaml#L15-L22

The solution will be just change it to [**.Values.config.worker.podAnnotations** and **.Values.config.coordinator.podAnnotations** ] so the deployment can get the correct podAnnotations for worker and coordinator. This is important when doing specific configs like openmetrics for example where each config must have the name of the container so we can fine tune each pod.

I can do the change just want to check what you think first.

**Comment by valeriano-manassero** [comment]
If you have a PR to propose is more then welcome for me 😃
Feel free to propose one to discuss.

**Comment by jkleinkauff** [comment]
Will do that, thank you!
