### ISSUE TITLE
use pattern or dataview instead of index name in elasticsearch

### ISSUE THREAD

**Issue by therus000** [valeriano-manassero/helm-charts#154]
good day
thanx for helm. all work nice
but i got question. i connect my elastic to trino. and the trinodb to metabase. all work fine
but the only thing that i cant figure is how to use index pattern instead of index separately
can u help please, or is it possible?

**Comment by valeriano-manassero** [comment]
Hi @therus000 ,
this is something more application related than Helm chart one.

I suggest to post this question on TrinoDB support so you can get better advice; if anything then, will be needed from chart perspective let me know, I will be glad to help.
