### ISSUE TITLE
Support of password authenticators other then file

### ISSUE THREAD

**Issue by bhamdouni** [valeriano-manassero/helm-charts#169]
With `http-server.authentication.type=PASSWORD ` Trino supports 3 different password authenticatos: file, ldap and salesforce
https://trino.io/docs/current/security/authentication-types.html

The Helm Chart doesn't permit any other auhenticator then file when authentication type is PASSWORD

Maybe using a more generic .Values.config.general.passwordAuthenticatorProperties could help

**Comment by valeriano-manassero** [comment]
I guess it can be a good idea to parametrize file generation so it can be avoided to produce ldap and salesforce config.

Do you think you can produce a PR about this topic?
