### ISSUE TITLE
[trino] Restore ability to provide fault tolerance config without b64 encoded secret

### ISSUE THREAD

**Issue by cccs-nik** [valeriano-manassero/helm-charts#194]
### Is your feature request related to a problem ?

The ability to provide the fault tolerance config "normally" like it was possible before was removed for apparently no good reason in the following PR: https://github.com/valeriano-manassero/helm-charts/pull/173

### Describe the solution you'd like.

Make the option to use a b64 encoded secret for the fault tolerance config configurable

### Describe alternatives you've considered.

.

**Comment by valeriano-manassero** [comment]
@ndrluis can you pls chime in on this one? I'd like to understand if there's a specific reason I'm missing right now. Ty.

**Comment by cccs-nik** [comment]
Any chance we could get this going? @valeriano-manassero

**Comment by valeriano-manassero** [comment]
Sorry, very busy in these days but lgtm and merged (and chart released). ty!
