### ISSUE TITLE
Use standard helm annotations

### ISSUE THREAD

**Issue by cep21** [valeriano-manassero/helm-charts#26]
Hi,

I noticed you have
```
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
```

In your helm chart.  The standard annotations are documented here: https://helm.sh/docs/chart_best_practices/labels/

Can you use the standard annotations in your templates?

Thanks!

**Comment by valeriano-manassero** [comment]
Hi @cep21 ,
thank you for pointing me on this, will work on it soon and post updates here!

**Comment by valeriano-manassero** [comment]
hi @cep21 ,
chart version 1.2.5 released. Please let me know if the improvements are working for you.
Thanks!

**Comment by cep21** [comment]
Thanks!
