### ISSUE TITLE
Update template to support trino-docker verison 352

### ISSUE THREAD

**Issue by aakashnand** [valeriano-manassero/helm-charts#40]
Currently, according to [documentation for trino-docker version 351](https://github.com/trinodb/trino/tree/297ba4d58a526667d91b9685b453faafa869c68f/core/docker) configuration is expected to be mounted to either to `/etc/trino` or `/usr/lib/trino/etc` (the latter takes precedence). If neither of these exists then the default single node configuration will be used but in the upcoming release `352` the configuration is expected to only `etc/trino`. So we need to update the helm-charts accordingly as `health_check.sh` is not getting executed because configmap is mounting it as a read-only file under new directory `/etc/trino`

Reference: 
https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/release/release-351.md#docker-image
https://trino.io/blog/2021/01/04/migrating-from-prestosql-to-trino.html => Docker Image section

**Comment by valeriano-manassero** [comment]
We can work on referred PR, it should be easy to get a new chart deployed.

About `health_check.sh`, I never liked that approach since it's confusing to have a bash script in the middle of config files. I can fix it with a specific PR soon.

**Comment by valeriano-manassero** [comment]
Will do a new PR very soon for health_check fix

**Comment by valeriano-manassero** [comment]
https://github.com/valeriano-manassero/helm-charts/pull/43 should improve health check too (chart version 1.0.2).
