### ISSUE TITLE
multiple instance catalog?

### ISSUE THREAD

**Issue by letmagnau** [valeriano-manassero/helm-charts#44]
can I have multiple catalog of the same type?
like two instance of ES??

as 

 elasticsearch.properties: |-
      connector.name=elasticsearch1
      elasticsearch.host=xxxxxxxxxxxxxxxxxxxx
      elasticsearch.port=xxx
      elasticsearch.default-schema-name=default
      elasticsearch.tls.enabled=true
      elasticsearch.security=PASSWORD
      elasticsearch.auth.user=xxxxxxxxxx
      elasticsearch.auth.password=xxxxxxxxx
      elasticsearch.ignore-publish-address=true
     |-
      connector.name=elasticsearch2
     elasticsearch.host=
    elasticsearch.port=
      elasticsearch.default-schema-name=default
     elasticsearch.tls.enabled=true
      elasticsearch.security=PASSWORD
      elasticsearch.auth.user=-
      elasticsearch.auth.password=
      elasticsearch.ignore-publish-address=true

**Comment by valeriano-manassero** [comment]
hi,
basically these values are going to generate the configs files so:
```
connectors:
  elasticsearch1.properties: |-
    connector.name=elasticsearch1
    elasticsearch.host=xxxxxxxxxxxxxxxxxxxx
    elasticsearch.port=xxx
    elasticsearch.default-schema-name=default
    elasticsearch.tls.enabled=true
    elasticsearch.security=PASSWORD
    elasticsearch.auth.user=xxxxxxxxxx
    elasticsearch.auth.password=xxxxxxxxx
    elasticsearch.ignore-publish-address=true
  elasticsearch2.properties: |-
    connector.name=elasticsearch2
    elasticsearch.host=
    elasticsearch.port=
    elasticsearch.default-schema-name=default
    elasticsearch.tls.enabled=true
    elasticsearch.security=PASSWORD
    elasticsearch.auth.user=-
    elasticsearch.auth.password=
    elasticsearch.ignore-publish-address=true
```

Is this what are you trying to achieve?

**Comment by letmagnau** [comment]
I 'will try and get you feedback soon , tnx

**Comment by letmagnau** [comment]
No, non funziona :)

  ERROR    main    io.trino.server.Server    No factory for connector 'elasticsearch2'.  Available factories: [memory, kudu, blackhole, kinesis, redis, accumulo, gsheets, raptor-leg │
│ java.lang.IllegalArgumentException: No factory for connector 'elasticsearch2'.  Available factories: [memory, kudu, blackhole, kinesis, redis, accumulo, gsheets, raptor-legacy, elasticsearch, jmx, postgresql │
│     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)                                                                                                                               │
│     at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:188)                                                                                                                             │
│     at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)                                                                                                                             │
│     at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)                                                                                                                            │
│     at io.trino.server.Server.doStart(Server.java:119)                                                                                                                                                          │
│     at io.trino.server.Server.lambda$start$0(Server.java:73)                                                                                                                                                    │
│     at io.trino.$gen.Trino_352_131_gab136fe_dirty____20210309_092311_1.run(Unknown Source)                                                                                                                      │
│     at io.trino.server.Server.start(Server.java:73)                                                                                                                                                             │
│     at io.trino.server.TrinoServer.main(TrinoServer.java:38)
