### ISSUE TITLE
Trino node.id

### ISSUE THREAD

**Issue by raftAtGit** [valeriano-manassero/helm-charts#47]
Hello,

First, thanks for sharing this :)

In [Trino deployment guide](https://trino.io/docs/current/installation/deployment.html) it's mentioned that minimal configuration should contain a unique `node.id` for each node. 

However, in your Trino Helm charts, no such value exists in `/etc/trino/node.properties` files. 

How is this working in this case?

**Comment by valeriano-manassero** [comment]
Afaik not declaring an id means the node will use a random one.
About the lifecycle management, if a k8s node fails or you rollout an update, the pods are never restarted but recreated so it\s like you are going to join new TrinoDB nodes to the cluster. This is the usual behaviour in k8s where resources are ephemeral.

In my TrinoDB installation I don't have any issue also rolling out updates transparently; let me know if I can help in any way improving the chart if needed!

**Comment by valeriano-manassero** [comment]
Just a small correction after some discussion on TrinoDB slack channel: if a `node.id` is not declared in the config file, TrinoDB will use the hostname. In a k8s pod the hostname is the name of the pod itself so it's unique in this case since it's generated by the deployment.

**Comment by raftAtGit** [comment]
thanks, that is good to know :) 
this also means, if a worker node crashes, it will get the same id when restarted by the deployment

**Comment by valeriano-manassero** [comment]
> this also means, if a worker node crashes, it will get the same id when restarted by the deployment

If a node crashes K8s will spawn another one with a new id and this will be automatically joined to the cluster.
In a physical environment it is like removing a broken node and adding a new one, simply in this case is don automatically by the orchestrator (k8s).

**Comment by raftAtGit** [comment]
well, if a pod crashes, K8S (or `Deployment` to be precise) will spawn another pod with same name. and HOSTNAME of the pod is the name of the pod (at least this is the default behavior)

so in this case worker node's (pod's) id in Trino will not change

**Comment by valeriano-manassero** [comment]
In a test environment I have :

```
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
test-trino-coordinator   1/1     1            1           19m
test-trino-worker        3/3     3            3           19m
```

than results in these pods:

```
NAME                                         READY   STATUS    RESTARTS   AGE
test-trino-coordinator-7f6fc8794-kj84m       1/1     Running   0          21m
test-trino-worker-66dd98fdf9-8dffk           1/1     Running   0          21m
test-trino-worker-66dd98fdf9-gv9gq           1/1     Running   0          21m
test-trino-worker-66dd98fdf9-j7pb8           1/1     Running   0          21m
```

let's kill the latest pod (hostname is `test-trino-worker-66dd98fdf9-j7pb8`) so k8s is creating a new one to replace it:

```
NAME                                         READY   STATUS    RESTARTS   AGE
test-trino-coordinator-7f6fc8794-kj84m       1/1     Running   0          21m
test-trino-worker-66dd98fdf9-8dffk           1/1     Running   0          21m
test-trino-worker-66dd98fdf9-gv9gq           1/1     Running   0          21m
test-trino-worker-66dd98fdf9-an4oo           1/1     Running   0           1m
```

As you can see new instance have a new hostname so a different `trino.id` because deployment append an id to pods name that is random.

Is this the behaviour you are interested in or am I missing something?

**Comment by raftAtGit** [comment]
I guess you deleted the pod, right? that doesn't mimic crashing. in the list you provided `RESTARTS ` is 0 for all of them.

exec into the pod and kill the main (Java) process, that will mimic the crash. the pod will restart with the same name and this will be reflected in the list under `RESTARTS `

**Comment by valeriano-manassero** [comment]
Ok I get your point.

If a pod crash or liveness probe fails it is restarted and this is the case you are thinking about.

But remember that a k8s node can crash or became NotReady. Moreover any update of the deployment will trigger the rollout. These cases will force k8s to reconcile with new pods but this is ok since they will automatically join the cluster so it should be ok for your use case.

**Comment by raftAtGit** [comment]
that's correct. I just wanted to emphasize, in the case of Trino node crash, their id's do not change.

**Comment by valeriano-manassero** [comment]
Sure, sorry for the misunderstanding I was referring k8s node because from my point of view Trino instance is apt but it's true that is a Trino node.

So issue solved 😄

**Comment by raftAtGit** [comment]
no worries :)
