### ISSUE TITLE
Trino UI not accepting Password Authentication 

### ISSUE THREAD

**Issue by sbbagal13** [valeriano-manassero/helm-charts#68]
Hi All, 

I am running trino with below authentication type in **values.yaml**  and also providing required details for password.db file 
authenticationType: "PASSWORD"  

auth:
      passwordAuth: "admin:$2y$10$anRhQud6EGUKIX9Wfsz.DOwTxPZiMnhjcq6LaUv6m8Ldxom0DaRVG"

It is creating required file and data in config directory
**cat /etc/trino/password-authenticator.properties** 
password-authenticator.name=file
file.password-file=/etc/trino/auth/password.db

**cat /etc/trino/auth/password.db**
admin:$2y$10$anRhQud6EGUKIX9Wfsz.DOwTxPZiMnhjcq6LaUv6m8Ldxom0DaRVG

But UI login page not reflecting it , it accept any username and "Password Not Allowed" in password text 
Any suggestion to resolve this will be very helpful ..

Thanks to all for continuous improvement and support

**Comment by valeriano-manassero** [comment]
Hi,
are you using TLS?

As mentioned here: https://trino.io/docs/current/security/overview.html TLS is a requirement to enable passwords.

**Comment by sbbagal13** [comment]
No , I haven't done any setting for TLS 
Do we have any setting parameter to configure in Chart to enable it?

**Comment by valeriano-manassero** [comment]
From my point of view, the easiest way is to install an ingress controller (like nginx) with its official chart and add in ingress with TLS pointing to trino service.

**Comment by valeriano-manassero** [comment]
Will keep this open, I'm thinking about adding ingress to the chart soon.

**Comment by valeriano-manassero** [comment]
@sbbagal13 you may give a try to the latest chart version `1.2.0` that now have an `ingress` section where you can also set the TLS secret containing the certificates.

**Comment by sbbagal13** [comment]
Hi @valeriano-manassero , Thanks for enhancement in chart.  Do we need load balancer to use Ingress ?
When I enable ingress and add updated processForwarded=true , then webui getting disabled and if I put it as false then its showing UI without needing password, am I missing anything in configuration?

**Comment by valeriano-manassero** [comment]
> Do we need load balancer to use Ingress ?

It depends on your cluster configuration. You need a working ingress controller and often a load balancer.

> When I enable ingress and add updated processForwarded=true , then webui getting disabled and if I put it as false then its showing UI without needing password, am I missing anything in configuration?

Can you please share your values and what kind of k8s cluster are you using?

I also suggest to ask for help in Trino official Slack channel just to have a more meaningful help.

**Comment by sbbagal13** [comment]
I am using k8s on openshift, I don't want loadbalancer at this point but with ingress enable its not making any difference than last release. ingress is getting created as per given hostname.

**Comment by valeriano-manassero** [comment]
I'd suggest to check Ingress Controller that is applying the Ingress rule, especially for access logs containing requests you sent eventually increasing logging level. Maybe in this way we can see some evidence and try to understand what is going on.

**Comment by sbbagal13** [comment]
okay, I will try to get more details on it. also I see one warning while deploying the chart regarding ingress

W0702 12:42:36.292971   90166 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by valeriano-manassero** [comment]
> W0702 12:42:36.292971   90166 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

This is simply a warning because I noticed I did a mistake in the version selector of the ingress. Don't worry, this is not a problem but I will release a fix for it. I guess you are using k8s 1.19.

**Comment by valeriano-manassero** [comment]
Warning should now be fixed.

About config for password to work:
* create a tls secret (example here: https://kubernetes.github.io/ingress-nginx/user-guide/tls/)
* enable ingress setting hostname and tls secret name
* enable `processForwarded` and set `authenticationType` to `PASSWORD`
* set `auth` adding a user

With these steps you should be able to see the password request in the UI.

Just one note: it may be possible you need to restart all the pods if you change a password. This will be addressed on a PR soon.

**Comment by valeriano-manassero** [comment]
> Just one note: it may be possible you need to restart all the pods if you change a password. This will be addressed on a PR soon.

no more needed in latest chart release

**Comment by sbbagal13** [comment]
Thank you @valeriano-manassero , Its perfectly working as expected !!!

**Comment by sbbagal13** [comment]
@valeriano-manassero: Do I need to add any certificate configurations to coordinator config to use CLI ? After above configuration my UI is working fine as expected (user/password) but I am not able to query to Trino from CLI from coordinator pod
Getting error: Error running command: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
any suggestion?

**Comment by valeriano-manassero** [comment]
Launching trino cli directly from a Trino pod will connect to svc without using the ingress. To avoid this problem you should specify the url of the ingress or avoid to use ingress and setup tls directly into Trino.
