### ISSUE TITLE
Observation: Configuration parameter duplicate in template

### ISSUE THREAD

**Issue by sbbagal13** [valeriano-manassero/helm-charts#80]
Hi @valeriano-manassero , I observed in configmap-coordinator.yaml and configmap-worker.yaml the memory configuration property (query.max-memory) is duplicated (find below snippet) with different values 

    **query.max-memory={{ .Values.server.config.query.maxMemory }}**
    query.max-memory-per-node={{ .Values.server.config.query.maxMemoryPerNode }}
    **query.max-memory={{ .Values.server.config.query.maxTotalMemory }}**

I think it should be like below 
    **query.max-memory={{ .Values.server.config.query.maxMemory }}**
    query.max-memory-per-node={{ .Values.server.config.query.maxMemoryPerNode }}
    **query.max-total-memory={{ .Values.server.config.query.maxTotalMemory }}**

**Comment by valeriano-manassero** [comment]
Ty for pointing me on this; will produce a fix ASAP.

**Comment by valeriano-manassero** [comment]
Fixed in Trino 1.3.1.
