### ISSUE TITLE
Can support HTTPS and TLS config?

### ISSUE THREAD

**Issue by l0ginp** [valeriano-manassero/helm-charts#85]
Hi, This chart can support HTTPS and TLS config in below this?
https://trino.io/docs/current/security/tls.html

Thanks

**Comment by valeriano-manassero** [comment]
Ho @l0ginp ,
best way to have https/tls (and maybe password authentication is to use this procedure:

* create a tls secret (example here: https://kubernetes.github.io/ingress-nginx/user-guide/tls/)
* enable ingress setting hostname and tls secret name
* enable processForwarded and set authenticationType to PASSWORD
* set auth adding a user

Does this help you?

**Comment by l0ginp** [comment]
Nice thanks !
