### ISSUE TITLE
Add change log releases tags

### ISSUE THREAD

**Issue by l0ginp** [valeriano-manassero/helm-charts#89]
Can you add change log releases tags to know which part has changed.

**Comment by l0ginp** [comment]
Sorry, i dont know how to automate on this area :(
but I can help you in other area like PR.

**Comment by valeriano-manassero** [comment]
Ok, will check if some gh action already exists and I will be able to integrate it; will take some time but I will update you here.

**Comment by valeriano-manassero** [comment]
On next release changeling should be generated automatically.
