### ISSUE TITLE
Support imagePullSecrets

### ISSUE THREAD

**Issue by occho** [valeriano-manassero/helm-charts#97]
## Motivation

To support pulling docker image from a private registry for Kubernetes pods, I'd like to make it support configuring imagePullSecrets.

## References

- Kubernetes guide about pulling image from private registry: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
- Sample implementations:
  - https://github.com/trinodb/charts/pull/17
  - https://github.com/occho/helm-charts/tree/image-pull-secret

**Comment by valeriano-manassero** [comment]
Version 1.9.0 is out with this implementation, let me know if it works

**Comment by occho** [comment]
It works! Thank you for quickly handling this!
