### ISSUE TITLE
Support secret mount for worker deployment

### ISSUE THREAD

**Issue by occho** [valeriano-manassero/helm-charts#98]
## Motivation

I wish to have secret mount support for worker deployment as well as coordinator as implemented in #87 . For example, to enable Kerberos authentication, I want to install keytab file in worker node via kubernetes secret.

**Comment by valeriano-manassero** [comment]
I need to do some tests before publishing a PR on that, will do this in some day I think.

**Comment by valeriano-manassero** [comment]
Unfortunately I'm pretty busy right now, if possible a PR would be very welcome, if not I will need some more time 🙏

**Comment by fcomuniz** [comment]
What kind of tests would be needed? i am willing to help on the PR
